trigger:
- main

pool:
  vmImage: 'windows-latest'

name: '$(Date:%y).$(DayOfYear).$(Rev:r)'

steps:
- task: DotNetCoreCLI@2
  displayName: Build and zip to the staging directory
  inputs:
    command: publish
    projects: src/number-sequence.sln
    arguments: '-c Debug -o $(Build.ArtifactStagingDirectory)/output'
    zipAfterPublish: true
    modifyOutputPath: true

- task: CopyFiles@2
  displayName: Copy deployment files to output
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/deployment/
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: Container
