# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

name: '$(Date:y).$(DayOfYear).$(Rev:r)'

steps:
# Build and copy to the staging directory
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    projects: src/number-sequence.sln
    arguments: '-c Debug -o $(Build.ArtifactStagingDirectory)/output'
    zipAfterPublish: true
    modifyOutputPath: true

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container'
